### ISSUE TITLE
Move all jobs in the GitHub workflows to run on private GitHub runners

### ISSUE THREAD

**Issue by GImbrailo** [ecadlabs/taquito#819]
**Is your feature request related to a problem and use case? Please describe.**
Some of the jobs in the workflows are running on public runners and should be configured to run on private runners. This will enable internal communication with the node RPC interfaces when running integrations tests. An example of the configuration to run on public runners is as follows:
```yaml
jobs:
  integration-tests-edonet:
    runs-on: ubuntu-latest
```

**Describe the solution you'd like**
The workflows should be configured to run on private runners as follows:
```yaml
jobs:
  integration-tests-edonet:
    runs-on: self-hosted
```
